In [1]:
from dotenv import load_dotenv
import pandas as pd
import os
from sqlalchemy import create_engine

In [2]:
load_dotenv()   # fetch environment variable
engine = create_engine(os.getenv("VAERS_DATABASE_URL"))    # create engine from env

In [5]:
query = """SELECT COUNT(*) FROM symptoms_2025"""

In [6]:
pd.read_sql_query(query, engine)

   count
0  49044

In [11]:
query = """SELECT COUNT(DISTINCT("VAERS_ID")) FROM symptoms_2025"""

In [12]:
pd.read_sql_query(query, engine)

   count
0  40285

In [ ]:
query = """"""